### ISSUE TITLE
META : translation of content

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/cgov-digital-platform-acceptance-tests#383]
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/379
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/380
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/381
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/382
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/384
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/385
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/386
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/428
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/429
- [ ] https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/430
