### ISSUE TITLE
Spike: Parallelization of Cypress

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/cgov-digital-platform-acceptance-tests#461]
As we currently stand, it takes ~2 hours for the whole regression suite to execute - which is not ideal. What I'd like to try is to try running most of the features in several threads and see if it reduces the execution time

Plus we'd like to replace behat with cypress, but without multiple threads cypress takes longer to execute

there are several dependencies to try for cypress parallel, this is one of them https://github.com/tnicola/cypress-parallel 

> **ESTIMATE** TBD

- [ ] install the dependency and update npm test script to run with 2 threads ( does it work locally and is it faster?)

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by santwuma** [comment]
Completed spike. Solution in tickt #467
